<<<<<<< HEAD
const defaultBanner = "create-react2023 - a React template based on webpack5";
=======
const defaultBanner = 'create-react2023 - a React template based on webpack5'
>>>>>>> b988996d413af7fe0290d17aa26e54d4661dd8c0

// generated by the following code:
//
// require('gradient-string')([
//   { color: '#42d392', pos: 0 },
//   { color: '#42d392', pos: 0.1 },
//   { color: '#647eff', pos: 1 }
// ])('create-react2023 - a React template based on webpack5'))
//
// Use the output directly here to keep the bundle small.
const gradientBanner =
<<<<<<< HEAD
  "\x1B[38;2;66;211;146mc\x1B[39m\x1B[38;2;66;211;146mr\x1B[39m\x1B[38;2;66;211;146me\x1B[39m\x1B[38;2;66;211;146ma\x1B[39m\x1B[38;2;66;211;146mt\x1B[39m\x1B[38;2;66;211;146me\x1B[39m\x1B[38;2;67;209;149m-\x1B[39m\x1B[38;2;68;207;151mr\x1B[39m\x1B[38;2;69;205;154me\x1B[39m\x1B[38;2;69;203;157ma\x1B[39m\x1B[38;2;70;200;160mc\x1B[39m\x1B[38;2;71;198;162mt\x1B[39m\x1B[38;2;72;196;165m2\x1B[39m\x1B[38;2;73;194;168m0\x1B[39m\x1B[38;2;74;192;171m2\x1B[39m\x1B[38;2;75;190;173m3\x1B[39m \x1B[38;2;75;188;176m-\x1B[39m \x1B[38;2;76;186;179ma\x1B[39m \x1B[38;2;77;183;181mR\x1B[39m\x1B[38;2;78;181;184me\x1B[39m\x1B[38;2;79;179;187ma\x1B[39m\x1B[38;2;80;177;190mc\x1B[39m\x1B[38;2;80;175;192mt\x1B[39m \x1B[38;2;81;173;195mt\x1B[39m\x1B[38;2;82;171;198me\x1B[39m\x1B[38;2;83;169;201mm\x1B[39m\x1B[38;2;84;166;203mp\x1B[39m\x1B[38;2;85;164;206ml\x1B[39m\x1B[38;2;86;162;209ma\x1B[39m\x1B[38;2;86;160;211mt\x1B[39m\x1B[38;2;87;158;214me\x1B[39m \x1B[38;2;88;156;217mb\x1B[39m\x1B[38;2;89;154;220ma\x1B[39m\x1B[38;2;90;152;222ms\x1B[39m\x1B[38;2;91;149;225me\x1B[39m\x1B[38;2;92;147;228md\x1B[39m \x1B[38;2;92;145;230mo\x1B[39m\x1B[38;2;93;143;233mn\x1B[39m \x1B[38;2;94;141;236mw\x1B[39m\x1B[38;2;95;139;239me\x1B[39m\x1B[38;2;96;137;241mb\x1B[39m\x1B[38;2;97;135;244mp\x1B[39m\x1B[38;2;97;132;247ma\x1B[39m\x1B[38;2;98;130;250mc\x1B[39m\x1B[38;2;99;128;252mk\x1B[39m\x1B[38;2;100;126;255m5\x1B[39m";
export default { defaultBanner, gradientBanner };
=======
  '\x1B[38;2;66;211;146mc\x1B[39m\x1B[38;2;66;211;146mr\x1B[39m\x1B[38;2;66;211;146me\x1B[39m\x1B[38;2;66;211;146ma\x1B[39m\x1B[38;2;66;211;146mt\x1B[39m\x1B[38;2;66;211;146me\x1B[39m\x1B[38;2;67;209;149m-\x1B[39m\x1B[38;2;68;207;151mr\x1B[39m\x1B[38;2;69;205;154me\x1B[39m\x1B[38;2;69;203;157ma\x1B[39m\x1B[38;2;70;200;160mc\x1B[39m\x1B[38;2;71;198;162mt\x1B[39m\x1B[38;2;72;196;165m2\x1B[39m\x1B[38;2;73;194;168m0\x1B[39m\x1B[38;2;74;192;171m2\x1B[39m\x1B[38;2;75;190;173m3\x1B[39m \x1B[38;2;75;188;176m-\x1B[39m \x1B[38;2;76;186;179ma\x1B[39m \x1B[38;2;77;183;181mR\x1B[39m\x1B[38;2;78;181;184me\x1B[39m\x1B[38;2;79;179;187ma\x1B[39m\x1B[38;2;80;177;190mc\x1B[39m\x1B[38;2;80;175;192mt\x1B[39m \x1B[38;2;81;173;195mt\x1B[39m\x1B[38;2;82;171;198me\x1B[39m\x1B[38;2;83;169;201mm\x1B[39m\x1B[38;2;84;166;203mp\x1B[39m\x1B[38;2;85;164;206ml\x1B[39m\x1B[38;2;86;162;209ma\x1B[39m\x1B[38;2;86;160;211mt\x1B[39m\x1B[38;2;87;158;214me\x1B[39m \x1B[38;2;88;156;217mb\x1B[39m\x1B[38;2;89;154;220ma\x1B[39m\x1B[38;2;90;152;222ms\x1B[39m\x1B[38;2;91;149;225me\x1B[39m\x1B[38;2;92;147;228md\x1B[39m \x1B[38;2;92;145;230mo\x1B[39m\x1B[38;2;93;143;233mn\x1B[39m \x1B[38;2;94;141;236mw\x1B[39m\x1B[38;2;95;139;239me\x1B[39m\x1B[38;2;96;137;241mb\x1B[39m\x1B[38;2;97;135;244mp\x1B[39m\x1B[38;2;97;132;247ma\x1B[39m\x1B[38;2;98;130;250mc\x1B[39m\x1B[38;2;99;128;252mk\x1B[39m\x1B[38;2;100;126;255m5\x1B[39m'
export default { defaultBanner, gradientBanner }
>>>>>>> b988996d413af7fe0290d17aa26e54d4661dd8c0
